# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: Build@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    python -m venv venv
    source venv/bin/activate
  displayName: 'Create and start virtual environment'

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  
- script: |
  uses: actions/upload-artifact@v3
  with:
    name: python-app
    path: |
      . 
      !venv/
  displayName: 'Upload artifact for deployment jobs'


- task: Deploy@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'
